In [5]:
#1.Create a null vector of size 10 but the fifth value which is 1 

import numpy as np
null_vector = np.zeros(10)
null_vector[4]=1
null_vector


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [9]:
 #2.Create a vector with values ranging from 10 to 49
import numpy as np
vector = np.arange(10,50) 
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [11]:
#3.Reverse a vector
reversed_vector=np.flip(vector)
reversed_vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [13]:
#4.Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
#5.Find indices of non-zero elements from [1,2,0,0,4,0]
non_zero_indices = np.nonzero([1,2,0,0,4,0])
non_zero_indices

(array([0, 1, 4]),)

In [15]:
#6.Create a 3x3x3 array with random values
random_array = np.random.rand(3,3,3)
random_array

array([[[0.48903489, 0.65060194, 0.86663442],
        [0.60548348, 0.194943  , 0.9990504 ],
        [0.71187461, 0.93052547, 0.23407951]],

       [[0.20084114, 0.3735536 , 0.50523784],
        [0.25531662, 0.1312453 , 0.53700353],
        [0.1033988 , 0.86201006, 0.69530723]],

       [[0.40660554, 0.01395705, 0.80073476],
        [0.99896266, 0.70869661, 0.26808288],
        [0.93707139, 0.61380613, 0.94915244]]])

In [17]:
#7.Create a 10x10 array with random values and find the minimum and maximum values
random_values = np.random.rand(10,10)
min_value=random_values.min()
max_value=random_values.max()
print(min_value,max_value)


0.003014275719961601 0.9870610839930218


In [20]:
#8. Create a 2d array with 1 on the border and 0 inside
border_array = np .ones((10,5))
border_array[1:-1,1:-1] = 0
border_array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
#EXERCISE1
import pandas as pd
data={'APPLES':[30],'BANANAS':[21]}
df = pd.DataFrame(data)
print(df)

   APPLES  BANANAS
0      30       21


In [24]:
#EXERCISE2
import pandas as pd
data={'APPLES':[35,41],'BANANAS':[21,34]}
df = pd.DataFrame(data)
df.index = ['2017 Sales','2018 Sales']
print(df)

            APPLES  BANANAS
2017 Sales      35       21
2018 Sales      41       34


In [25]:
#EXERCISE3
import pandas as pd
data={'FLOUR':'4CUPS','MILK':'1CUP','EGGS':'2LARGE','SPAM':'1CAN'}
series = pd.Series(data,name='DINNER')
print(series)

FLOUR     4CUPS
MILK       1CUP
EGGS     2LARGE
SPAM       1CAN
Name: DINNER, dtype: object


In [26]:
#EXERCISE4 Check the outcome of this command
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}]) 

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [27]:
#EXERCISE5Check the outcome of this command
import pandas as pd
data = pd.Series([0.25,0.50,0.75,1],index=['a','b','c','d'])
'a' in data




True